import Head from 'next/head'
import styles from '../styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.css";

import dynamic from "next/dynamic";
const Map = dynamic(() => import("../components/map"), {
  ssr: false
});

export default function Home() {



  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <base href="/" target="_blank"></base>
      </Head>


      <Map />


      <footer className={styles.footer}>
        <a href="https://github.com/commitdev/zero" target="_blank">
          Powered by {'Zero'}
        </a>
      </footer>
    </div>
  )
}
